apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tst-microservice-smart-wallet.fullname" . }}
  labels:
    {{- include "tst-microservice-smart-wallet.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: azure-service-account-testnet
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tst-microservice-smart-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tst-microservice-smart-wallet.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: azure-service-account-testnet
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "API_ROOT"
              value : "../"
            - name: "USE_COMPRESSION"
              value : "true"

            - name: "DB_URI"
              value : "mongodb://10.1.1.4:27017?retryWrites=true&w=majority&maxIdleTimeMS=120000"
            - name: "NODE_ENV"
              value : "testnet"
            - name: "PORT"
              value : "80"

            - name: "VAULT_NAME"
              value: "smart-wallet"
            - name: "VAULT_SECRET_NAME"
              value: "smartwalletKey"

            - name: "ETH_CHAIN_ID"
              value: "11155111"
            - name: "BASE_CHAIN_ID"
              value: "84532"
            - name: "POLYGON_CHAIN_ID"
              value: "80002"
            - name: "ARBITRUM_CHAIN_ID"
              value: "421614"
            - name: "BNB_CHAIN_ID"
              value: "97"

            - name: "ETH_NODE_1"
              value: "https://eth-sepolia.g.alchemy.com/v2/CPvHmlpZ7KeyVaIgGY4rRAyswxsEzusD"
            - name: "ETH_NODE_2"
              value: "https://ethereum-sepolia-rpc.publicnode.com/"
            - name: "ETH_NODE_3"
              value: "https://endpoints.omniatech.io/v1/eth/sepolia/public"

            - name: "BASE_NODE_1"
              value: "https://base-sepolia.g.alchemy.com/v2/CPvHmlpZ7KeyVaIgGY4rRAyswxsEzusD"
            - name: "BASE_NODE_2"
              value: "https://sepolia.base.org"
            - name: "BASE_NODE_3"
              value: "https://base-sepolia.blockpi.network/v1/rpc/public"

            - name: "POLYGON_NODE_1"
              value: "https://polygon-amoy.g.alchemy.com/v2/CPvHmlpZ7KeyVaIgGY4rRAyswxsEzusD"
            - name: "ARBITRUM_NODE_1"
              value: "https://arb-sepolia.g.alchemy.com/v2/CPvHmlpZ7KeyVaIgGY4rRAyswxsEzusD"
            - name: "BNB_NODE_1"
              value: "https://bnb-testnet.g.alchemy.com/v2/CPvHmlpZ7KeyVaIgGY4rRAyswxsEzusD"
            
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}