replicaCount: 1

image:
  repository: coinswapregistry.azurecr.io/tst-microservice-smart-wallet
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: '__TAG__'

imagePullSecrets: [name: coinswap-registry]
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: false
  annotations: {}
  name: ''

podAnnotations: {}
podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ''
  annotations:
    cert-manager.io/issuer: 'letsencrypt-testnet'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: test-api.metaproprotocol.com
      paths:
        - path: /ms/smart-wallet/(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: tls-secret-1
      hosts:
        - test-api.metaproprotocol.com

resources:
  limits:
    cpu: 500m
    memory: 2048Mi
  requests:
    cpu: 20m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
